version: 3.8
#each container = a service
services:

   mysql:
     image: mysql
     container_name: mysql-db
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
     ports:
       - "${MYSQL_PORT}:3306"
     healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
     networks:
       - app-network

   backend:
     build: ./backend
     container_name: backend
     ports:
      - "5000:5000"
     depends_on: mysql
     #Start mysql FIRST, then backend.
     networks:
      - app-network
   frontend:
     build: ./frontend
     container_name: frontend
     depends_on: backend
     ports:
      - "8080:80"
     networks:
      - app-network

#Docker creates a single shared bridge network, So all services can talk.
networks:
     - app-network